<<<<<<< HEAD
name: Things That I don't Understand
author: Presteniko Septi Rahadian
baseurl: /
description: Blog for things that i don't know
github: http://www.github.com/cyclonstep
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: kaixza

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
=======
# Configurations
title:            Jekyll Gitbook
longtitle:        Jekyll Gitbook
author:           HE Tao
email:            sighingnow@gmail.com
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://sighingnow.github.io'
baseurl:          '/jekyll-gitbook'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji

theme: jekyll-theme-minimal
>>>>>>> 3fbcd98b024176365a80dd466e336bdce44fac43
